version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/SalesforceMobileSDK-Android

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      # All setup
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Get Node
          command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run:
          name: Install Node
          command: sudo apt-get install -y nodejs && node -v && npm -v
      - run:
          name:  Install Ruby
          command: sudo apt-get install ruby-full
      - run:
          name:  Install build-essentials
          command: sudo apt-get install build-essential
      - run:
          name:  Install Fastlane
          command: sudo gem install fastlane

      - run:
          name: Run Tests
          command: fastlane PR
