version: 2
jobs:
  build:
    docker:
      - image: brandonpage/salesforce-mobilesdk-android-docker-primary:0.0.3

    working_directory: ~/SalesforceMobileSDK-Android

    environment:
      - TERM: "dumb"
      - ADB_INSTALL_TIMEOUT: 10
      - ANDROID_NDK: '/opt/ndk/android-ndk-r10e'
      - BUILD_THREADS: 2 

    steps:
      - run:
          name:  Launch Emulator
          # name should be env variable 
          command: emulator64-arm -avd test22 -no-audio -no-window -no-boot-anim -gpu off
          #command: emulator -avd test23 -no-audio -no-window -no-boot-anim -gpu off
          background: true

      - checkout
      - run: ./install.sh

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies && ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name:  Wait for Emulator to boot
          command: source .circleci/ci-helper.sh && waitForAVD

      - run:
          name:  Run Tests
          halt_build_on_fail: false
          command: ./gradlew :libs:SalesforceAnalytics:connectedAndroidTest :libs:SmartStore:connectedAndroidTest :libs:SmartSync:connectedAndroidTest :libs:SalesforceHybrid:connectedAndroidTest :libs:SalesforceReact:assembleDebug --continue --no-daemon --profile --max-workers 2
          no_output_timeout: 1200 

      - store_artifacts:
          path: ./build/archives
          destination: archives
      - store_artifacts:
          path: ./build/reports
          destination: reports
      - store_artifacts:
          path: ./build/outputs
          destination: outputs
      - store_test_results:
          path: ./build/outputs/androidTest-results/connected/
