jobs:
  build:
    docker:
      - image: brandonpage/salesforce-mobilesdk-android-docker-primary:0.0.2

    working_directory: ~/SalesforceMobileSDK-Android

    environment:
      - TERM: "dumb"
      - ADB_INSTALL_TIMEOUT: 10
      - ANDROID_NDK: '/opt/ndk/android-ndk-r10e'
      - BUILD_THREADS: 2 

    steps:
      - run:
          name: Install Build Dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install ant autoconf automake g++ gcc libqt5widgets5 lib32z1 lib32stdc++6  make maven python-dev python3-dev qml-module-qtquick-controls qtdeclarative5-dev -y

      - checkout
      
      - run:
          name:  Create Emulator
          command: source .circleci/circle-ci-android-setup.sh && createAVD

      - run:
          name:  Launch Emulator
          command: source .circleci/circle-ci-android-setup.sh && launchAVD
          background: true

      - run:
          name: Create Android NDK Directory
          command: |
            if [[ ! -e /opt/ndk ]]; then
              sudo mkdir /opt/ndk
            fi
            sudo chown ${USER:=$(/usr/bin/id -run)}:$USER /opt/ndk

      - run:
          name: Install Android NDK
          command: source .circleci/circle-ci-android-setup.sh && getAndroidNDK

      - run:
          name:  Wait for Emulator to boot
          command: source .circleci/circle-ci-android-setup.sh && waitForAVD

      - run:
          name: Gradle Dependences (to avoid bug)
          command: ./gradlew dependencies || true && ./gradlew clean

      - run:
          name:  Run tests with Fastlane
          halt_build_on_fail: false
          command: fastlane All
          no_output_timeout: 1800
